### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by moio** [uyuni-project/hub-xmlrpc-api#21]
I would recommend at least those two options when it comes to configuration for this project:

 1- a plain file: JSON or even better something human-friendly like YAML or TOML, which in particular supports comments. Reasoning: this is probably the easiest way for users to provide configuration details for "plain VM" cases
 2- specifying the entire configuration via environment variables (either several environment variables or, if complexity is just too much, a single one directly containing a YAML/JSON blob).

Option 2- is recommended because of the [Twelve-factor app](https://12factor.net/) pattern, which is a set of design/implementation recommendations for apps to be run in containerized/cloud environments. It is my belief all new components should try to follow it to keep a door open for a more distributed future.

In principle, at least as at the moment we only have 3 variables, all of the above could be handled with just three commandline arguments. Options above factor in some later growth in complexity.

Note also that all values should have defaults if at all possible - just running the program with no configuration at all should work if possible.

**Comment by admd** [comment]
Hey @moio ,
Thank you for this. Jfyi we have now updated the spec file  https://build.opensuse.org/package/show/home:admehmood/hub-xmlrpc-api and introduced quite a few things which would help from useability POV. I would appreciate if you could just install the rpm and follow the guidelines and let us know if anything should be changed. Here is what we have changed.

 - An example JSON file with default values will be created at `/etc/hub/hub-xmlrpc-api-config.json` . At package installation, user will be notified to make sure variable points to correct hub instance.
-  We have followed logs guidelines for [Tweleve-factor](https://12factor.net/logs) app and simply 
route all the logs to syslog and then redirect to `/etc/hub/hub-xmlrpc-api.log`. 

- We have introduced logrotation as well for the  API logs

- A unit file has been added, we don't start hub-xmlrpc-api automatically but during installation we do mention steps to the user to enable it.
