### ISSUE TITLE
Error when running unicast.contentmanagement.createEnvironment

### ISSUE THREAD

**Issue by mbrookhuis** [uyuni-project/hub-xmlrpc-api#66]
Hi, when running the following code:
`#!/usr/bin/python`
`import xmlrpclib`  
`import itertools`
`HUB_URL = "http://localhost:2830/hub/rpc/api"`
`HUB_LOGIN = "hubadmin"`
`HUB_PASSWORD = "suse1234"`
`client = xmlrpclib.Server(HUB_URL, verbose=0)`
`loginResponse = client.hub.loginWithAutoconnectMode(HUB_LOGIN, HUB_PASSWORD)`
`hubSessionKey = loginResponse["SessionKey"]`
`client.unicast.contentmanagement.createProject(hubSessionKey, 1000010000, "mb-test", "mb-test", "mb-test")`
`client.unicast.contentmanagement.createEnvironment(hubSessionKey, 1000010000, "mb-test", "", "dev", "dev", "dev")`
`client.unicast.contentmanagement.createProject(hubSessionKey, 1000010001, "mb-test", "mb-test", "mb-test")`
`client.unicast.contentmanagement.createEnvironment(hubSessionKey, 1000010001, "mb-test", "", "dev", "dev", "dev")`
`#logout`
`client.hub.logout(hubSessionKey)`

you will end with the following error:

`Traceback (most recent call last):
  File "clm_create.py", line 18, in <module>
    client.unicast.contentmanagement.createEnvironment(hubSessionKey, 1000010000, "mb-test", "", "dev", "dev", "dev")
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1313, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1161, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 448, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 412, in _read_status
    raise BadStatusLine("No status line received - the server has closed the connection")
httplib.BadStatusLine: No status line received - the server has closed the connection
`
Attached the hub-xmlrpc-api.log with more error messages
[hub-xmlrpc-api.log](https://github.com/uyuni-project/hub-xmlrpc-api/files/5021283/hub-xmlrpc-api.log)

**Comment by chiaradiamarcelo** [comment]
Addressed. Thanks
